name: deploy

# Only run this when the master branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install linkify-it-py
        pip install myst-parser~=0.13
        
    - name: execute script
      run: |
        python scripts/create_toc.py
        
    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .
        
    # Push to server
    - name: rsync and ssh
      env:
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        REMOTE_DIR: ${{ secrets.REMOTE_TARGET }}
        LOCAL_DIR: "_build/html/"
        COURSE_NAME: "physicsbank"
      run: |
        mkdir ~/.ssh
        echo "$REMOTE_KEY" > ~/.ssh/id_rsa
        ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/id_rsa
        pwd
        ls -la
        rsync -avzr --delete $LOCAL_DIR $REMOTE_USER@$REMOTE_HOST:$REMOTE_DIR/$COURSE_NAME
